### ISSUE TITLE
Ability to setup a series of results and errors

### ISSUE THREAD

**Issue by devinivy** [ottogiron/weaselpecker#2]
I must say, this little module is quite brilliant for mocking waterline collections.  Is there any possibility that in the future one would be able to setup series of mixed results and errors?  Perhaps requiring that errors are `instanceof Error` would be a good limitation to make this feasible.

**Comment by osukaa** [comment]
You mean like `setResults` receives both results and errors and returns them in that order?

**Comment by devinivy** [comment]
Yeah, or a separate method.  Not entirely sure what the best API would be.

**Comment by devinivy** [comment]
If you give a certain spec a thumbs-up, I'd be happy to issue a PR.

**Comment by ottogiron** [comment]
I think that using setResults would be a good idea. I can't think a good use case for something like "setMixedResults".  We can even deprecate setErrors if we take the first approach. Let me think of this for a while.

**Comment by ottogiron** [comment]
@devinivy  I think we can go ahead and implement mixed results for setResults using your suggestion. If you can issue a PR that would be great.

**Comment by devinivy** [comment]
:+1: mind assigning this to me so I don't forget?

**Comment by ottogiron** [comment]
@devinivy released and published on npm. Thanks!!!

**Comment by devinivy** [comment]
Cheers! :beers:
