### ISSUE TITLE
Testing custom Model methods that call other model methods

### ISSUE THREAD

**Issue by infiniteluke** [ottogiron/weaselpecker#4]
I have a custom model method called "start" that calls model methods like findOne and update.

simplified ex:

``` javascript
  start: function(options, cb) {
        var job = options.job;
        Job.update(job.id, {status: 'In Progress', startedAt: Date()}).exec(function(err, updated) {
          if (err) return cb(err);
          // Populate the tasks on the newly updated Job
          Job.findOne(updated[0].id).populate('tasks').exec(function(err, job) {
            if (err) return cb(err);

            cb(null, job);
          });
        });
}
```

The use case you show in the documentation shows you creating a entire MockModel whereas I just want to stub the update and findOne calls inside of the start function. I still need to be able to call the actual start function in order to test it so mocking the whole model doesn't work for me.

Is weaselpecker built with this case in mind? I apologize if this is not the right channel for this question. 

Thanks!

**Comment by osukaa** [comment]
I don't know if what you want could be achieved through the use of custom methods for the model

``` javascript
var Model = weaselpecker.mock({
  extraModelMethods: ['findByID']
});

Model.setResults('findByID',  [fixture1, fixture2] );

Model.findByID({})
.exec(function(err, results){
  //extra logic here
});
```

This wasn't built with the idea of passing our models to mock, just mock a generic model.

**Comment by infiniteluke** [comment]
Here's what I ended up doing:

``` javascript
// Show example of stubbing findOne for a call to a custom model method

var options = {
        job: 123
      };

// Retain the custom model method that I want to test in a temp var called unit (it's the unit I'm testing).
var unit = Job.startNextTask;

// Job is a global and is required from the actual model file
// add the name of the custom model method I'm testing to the mock model.
Job = weaselpecker.mock({
  extraModelMethods: ['startNextTask']
});

// Add the actual function to the mock model so that I can be called like it normally would
Job.startNextTask = unit;

// Stub the results of findOne
Job.setResults('findOne', [undefined]);

// Calling the custom method on the mock model runs the code, but m ocks work too.
Job.startNextTask(options, function(err, job) {
  expect(err).not.to.be.be.null;
  expect(job).to.be.undefined;
  done();
});

```

It's dirty but it gets the job done. If you know of a better way to do this, let me know. I haven't looked closely at weaselpecker, but it seems like it wouldn't be hard to make this work. 

I'll create PR if I have time to work on something.

**Comment by ottogiron** [comment]
That's a good approach.  not  sure if you need  extraModelMethods: ['startNextTask'] in this case, because you're going to override that method  anyway. 

Let us know if you have cool ideas :).
